# Beverage.create({ name: 'Long Island', strength: 13 })
Beverage.create(name: 'sour', strength: 3)
Beverage.create(name: 'margarita', strength: 3)
Beverage.create(name: 'old fashioned', strength: 4)
Beverage.create(name: 'aviation', strength: 4)
Beverage.create(name: 'corpse reviver', strength: 5)
Beverage.create(name: 'long island', strength: 5)
Beverage.create(name: 'sangria', strength: 2)
Beverage.create(name: 'amf', strength: 5)
Beverage.create(name: 'ipa', strength: 4)
Beverage.create(name: 'red wine', strength: 2)
Beverage.create(name: 'holiday hooch', strength: 4)
Beverage.create(name: 'white claw', strength: 2)
Beverage.create(name: 'nigori', strength: 2)
Beverage.create(name: 'angry_orchard', strength: 2)
Beverage.create(name: 'oaxacan old fashioned', strength: 4)
Beverage.create(name: 'single malt scotch', strength: 5)
Beverage.create(name: 'cognac', strength: 5)
Beverage.create(name: 'manhattan', strength: 5)
Beverage.create(name: 'kentucky mule', strength: 4)
Beverage.create(name: 'somaek', strength: 2)
